### ISSUE TITLE
BC_LED_MODE_BLINK_* actual speed?

### ISSUE THREAD

**Issue by berkas1** [bigclownlabs/bcf-sdk-core-module#131]
What is the actual delay between state changes defined by
- BC_LED_MODE_BLINK_SLOW
- BC_LED_MODE_BLINK_FAST
- BC_LED_MODE_BLINK
- BC_LED_MODE_FLASH

I don't see it described in documentation. Thanks.

**Comment by hubpav** [comment]
That is right, but actually we cannot say exactly how much is SLOW or FAST since it is configurable. These flashing / blinking states are defined by a so-called "patterns" which is simply alternating sequence of "1" and "0" where each bit in the mask represent a so-called "slot" - slot is by default 100 ms but can be changed using a "set_slot_interval" call. So if you have pattern 0xaaaaaaaa , then the LED will blink 100 ms ON and 100 ms OFF (typically). Using this you can do some fancy stuff like 0xa000a000 - means two short blinks and long delay between them. You do not have to use these predefined blink modes but there is also a call for the custom blinking pattern. Happy blinking! :smile:
